import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import Image from "next/image";
import {PopoverGroup} from "@headlessui/react";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="dark:bg-gray-950 dark:text-white">
                <header>
                    <nav aria-label="Global"
                         className="container mx-auto px-2 py-8 sm:px-0 flex items-center justify-between">
                        <div className="flex lg:flex-1">
                            <Link href={'/'}>
                                <Image src={'/logo.webp'} alt={'Website logo'} width={200} height={100} loading={"eager"} />
                            </Link>
                        </div>
                        <PopoverGroup className="hidden lg:flex lg:gap-x-12">
                            <Link href={'/articles'} className="text-sm font-semibold leading-6">
                                Blog
                            </Link>
                            <Link href={'/articles'} className="text-sm font-semibold leading-6">
                                Search specific
                            </Link>
                        </PopoverGroup>
                        <div className="hidden lg:flex lg:flex-1 lg:justify-end">
                            <a href="#" className="text-sm font-semibold leading-6">
                                Log in <span aria-hidden="true">&rarr;</span>
                            </a>
                        </div>
                    </nav>
                </header>
                <main className="container mx-auto px-2 sm:px-0">{children}</main>
            </body>
        </html>
    );
}
